Exercise4
luizptm/SOM_training_LuizPaulo pull request #3
Opened 2022-10-24 17:23 UTC by luizptm

2022-10-26 16:15 UTC, RobertoEhlertOSF requested changes
Please leave here only the custom fields

2022-10-26 16:16 UTC, RobertoEhlertOSF requested changes

2022-10-26 16:16 UTC, RobertoEhlertOSF commented on force-app/main/default/objects/Order/fields/AccountNumber.field-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please leave only the custom fields

2022-11-04 14:27 UTC, luizptm commented
> Please leave here only the custom fields

It's done.

2022-11-23 18:20 UTC, merged